### ISSUE TITLE
сделать файлы всех проектов невидимыми

### ISSUE THREAD

**Issue by lizaku** [elmiram/hselingprojects#13]
Незалогиненные пользователи не видят файлы ни для каких работ!

**Comment by lizaku** [comment]
Или это не надо? Но в любом случае не все же соглашались на демонстрацию своих работ

**Comment by elmiram** [comment]
файлы работ видны только зарегистрированным пользователям.

**Comment by lizaku** [comment]
Наверно, надо все-таки дифференцировать и какие-то делать видимыми... Не знаю, я пока запуталась.
