### ISSUE TITLE
Кликабельные поля и заголовки

### ISSUE THREAD

**Issue by lizaku** [elmiram/hselingprojects#18]
- [x] По клику на автора я бы хотела получать все работы студента, по клику на руководителя - все его подшефные работы. 

- [x] Вообще, посмотрите на кликабельность полей таблички, а также кликабельность заголовков для сортировки.

**Comment by elmiram** [comment]
сделан первый пункт.

**Comment by elmiram** [comment]
сделан второй пункт.
